### ISSUE TITLE
cabal install breve fails with Web.Spock.Safe error

### ISSUE THREAD

**Issue by BooneJS** [rnhmjoj/breve#1]
(snip downloading packages)

> Downloading breve-0.4.3.0...
> Configuring breve-0.4.3.0...
> Building breve-0.4.3.0...
> Failed to install breve-0.4.3.0
> Build log ( /Users/b/.cabal/logs/breve-0.4.3.0.log ):
> cabal: Entering directory '/var/folders/56/46f3sr8n4fn7b41ppxh7f_q40000gn/T/cabal-tmp-72028/breve-0.4.3.0'
> Configuring breve-0.4.3.0...
> Building breve-0.4.3.0...
> Preprocessing executable 'breve' for breve-0.4.3.0...
> [1 of 7] Compiling Views            ( src/Views.hs, dist/build/breve/breve-tmp/Views.o )
> 
> src/Views.hs:10:1: error:
>     Failed to load interface for ‘Web.Spock.Safe’
>     Perhaps you meant
>       Web.Spock.Core (needs flag -package-key Spock-core-0.11.0.0)
>     Use -v to see a list of the files searched for.
> cabal: Leaving directory '/var/folders/56/46f3sr8n4fn7b41ppxh7f_q40000gn/T/cabal-tmp-72028/breve-0.4.3.0'
> Updating documentation index
> /Users/b/Library/Haskell/share/doc/x86_64-osx-ghc-8.0.1/index.html
> cabal: Error: some packages failed to install:
> breve-0.4.3.0 failed during the building phase. The exception was:
> ExitFailure 1

Failure reported in Hackage as well: https://hackage.haskell.org/package/breve-0.4.3.0/reports/

**Comment by rnhmjoj** [comment]
Yeah, it seems the Spock API has changed. I'm looking into it.

**Comment by rnhmjoj** [comment]
It should build now.
